stages:
  - unittest
  - exampletest
  - name: dockerbuild
    if: branch = master
  - name: website
    if: branch = master AND type != pull_request
  - name: sourcedocs
    if: branch = master AND type != pull_request

.elixir-env: &elixir-env
  language: elixir
  elixir: "1.10"
  otp_release: "22.0"

jobs:
  include:
    - stage: unittest
      <<: *elixir-env
      env:
        - MIX_ENV=test
      arch: amd64
      script:
        - mix test
        - mix credo --ignore-checks Design
    - stage: unittest
      <<: *elixir-env
      env:
        - MIX_ENV=test
      arch: arm64
      script:
        - mix test
        - mix credo --ignore-checks Design    
    - stage: exampletest
      language: node_js
      arch: amd64
      node_js:
        - "10"
      addons:
        apt:
          packages:
            - libgconf-2-4
      cache:
        npm: true
        directories:
          - ~/.cache
      script:
        - cd examples/tests
        - npm ci
        - npm run cypress:run:all
    - stage: exampletest
      language: node_js
      arch: arm64
      node_js:
        - "10"
      addons:
        apt:
          packages:
            - libgconf-2-4
      cache:
        npm: true
        directories:
          - ~/.cache
      script:
        - cd examples/tests
        - npm ci
        - npm run cypress:run:all    
    - stage: dockerbuild
      language: minimal
      arch: amd64
      services:
        - docker
      script:
        - docker build .
    - stage: website
      language: node_js
      node_js:
        - "8"
      cache:
        yarn: true
      script:
        - git config --global user.name "${GH_NAME}"
        - git config --global user.email "${GH_EMAIL}"
        - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
        - cd website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages
     stage: dockerbuild
      language: minimal
      arch: arm64
      services:
        - docker
      script:
        - docker build .
    - stage: website
      language: node_js
      node_js:
        - "8"
      cache:
        yarn: true
      script:
        - git config --global user.name "${GH_NAME}"
        - git config --global user.email "${GH_EMAIL}"
        - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
        - cd website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages    
    - stage: sourcedocs
      <<: *elixir-env
      arch: amd64
      script:
        - git config --global user.name "${GH_NAME}"
        - git config --global user.email "${GH_EMAIL}"
        - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
        - GIT_USER="${GH_NAME}" mix publish_gh_pages
    - stage: sourcedocs
      <<: *elixir-env
      arch: arm64
      script:
        - git config --global user.name "${GH_NAME}"
        - git config --global user.email "${GH_EMAIL}"
        - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
        - GIT_USER="${GH_NAME}" mix publish_gh_pages    
